name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -la
          echo "--- Prediction ---"
          ls -la Prediction || true


      - name: Push to Heroku via Git
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: s.goler3012@student.nu.edu
        run: |
          git config user.email "s.goler3012@student.nu.edu"
          git config user.name "github-actions[bot]"
          git remote remove heroku 2>/dev/null || true
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/breast-cancer-deploy.git
          git push heroku HEAD:main -f
